apiVersion: apps/v1
kind: Deployment
metadata:
  name: hw-deployment
  labels:
    app: hwapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hwapp
  template:
    metadata:
      labels:
        app: hwapp
    spec:
      containers:
      - name: server
        image: danieliko/hwapp
        ports:
        - containerPort: 3000
        
---

apiVersion: v1
kind: Service
metadata:
  name: hw-service
spec:
  selector:
    app: hwapp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000